# Copyright 2026 NXP
# SPDX-License-Identifier: Apache-2.0

CONFIG_KNXIOT_LIB=y

CONFIG_GPIO=y
CONFIG_INPUT=y

CONFIG_REQUIRES_FULL_LIBC=y
CONFIG_POSIX_API=y

# KNX IoT configuration
CONFIG_OC_USE_KNX_PORT_LAYER_ENABLED=y

# KNX IoT debug
CONFIG_OC_PRINT_ENABLED=y
CONFIG_OC_DEBUG_ENABLED=y
CONFIG_OC_DEBUG_OSCORE_ENABLED=y
CONFIG_LIB_KNX_LOG_LEVEL=4
CONFIG_KNX_LOG_TO_ZEPHYR=y
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=4096

CONFIG_KNXIOT_SPAKE2P_MBEDTLS=n
CONFIG_KNXIOT_SPAKE2P_PSA=y

CONFIG_KNXIOT_APP_LSXB_CHANNELS=1

# Use NVS as settings backend
CONFIG_NVS=y

# Logging
CONFIG_LOG=y
CONFIG_NET_LOG=y

CONFIG_NET_STATISTICS=y
CONFIG_PRINTK=y

# MbedTLS configuration
CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_BUILTIN=y
CONFIG_MBEDTLS_ENABLE_HEAP=y
CONFIG_MBEDTLS_HEAP_SIZE=30000
CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN=2048

# MbedTLS PSA Crypto configuration
CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_BUILTIN=y
CONFIG_MBEDTLS_ENABLE_HEAP=y
CONFIG_MBEDTLS_HEAP_SIZE=30000
CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN=2048
CONFIG_MBEDTLS_PSA_CRYPTO_C=y
CONFIG_PSA_WANT_KEY_TYPE_ECC_PUBLIC_KEY=y
CONFIG_PSA_WANT_KEY_TYPE_ECC_KEY_PAIR_IMPORT=y
CONFIG_PSA_WANT_KEY_TYPE_ECC_KEY_PAIR_EXPORT=y
CONFIG_PSA_WANT_ECC_SECP_R1_256=y
CONFIG_PSA_WANT_ALG_ECDSA=y
CONFIG_PSA_WANT_KEY_TYPE_RSA_PUBLIC_KEY=y
CONFIG_PSA_WANT_ALG_HKDF=y
CONFIG_PSA_WANT_ALG_HKDF_EXTRACT=y
CONFIG_PSA_WANT_ALG_HKDF_EXPAND=y
CONFIG_PSA_CRYPTO_ENABLE_ALL=y

# Ensure compatibility with MbedTLS API required for SPAKE2+
CONFIG_MBEDTLS_DECLARE_PRIVATE_IDENTIFIERS=y

# Networking shell
CONFIG_SHELL=y
CONFIG_NET_SHELL=n

# Memory monitoring configurations
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_NAME=y

# Optional: Enable runtime statistics
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_SCHED_THREAD_USAGE=y
CONFIG_SYS_HEAP_RUNTIME_STATS=y
