# Copyright 2026 NXP
# SPDX-License-Identifier: Apache-2.0

CONFIG_KNX_SENSOR=y
CONFIG_KNX_ACTUATOR=n

CONFIG_APPLICATION_NAME="KNX virtual sensor (LSSB)"
CONFIG_SN_LOWER_CASE="00fabeef0902"
CONFIG_KNX_IOT_PASSWORD="2X4W3TE0DFLLS19Y1FCH"

CONFIG_OC_REPLAY_PROTECTION_ENABLED=n

CONFIG_MAIN_STACK_SIZE=8096
CONFIG_KNX_THREAD_STACK_SIZE=12288
CONFIG_HEAP_MEM_POOL_SIZE=8192
